name: Build HGNC

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.3.1
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          sparse-checkout: |
            build.py
            docs/_data/manifest.yml
            export/hgnc/*
            export/hgnc.genegroup/*
          sparse-checkout-cone-mode: false
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update Git Configuration
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build HGNC resources
        id: update
        run: |
          uv run build.py -x hgnc -x hgnc.genegroup

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'ðŸ§¬ Update HGNC'
          default_author: github_actions
